### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by THausherr** [imalhasaranga/PDFLib#1]
Please find another name. "PDFBox" is a trademark of The Apache Software Foundation. What you do is like if you were constructing wheelbarrows and name them "Mercedes".

(I am a [PDFBox](http://pdfbox.apache.org/) committer, but I do not represent the Apache foundation)

**Comment by imalhasaranga** [comment]
Intention was to initiate a similar library like PDFBox to Php world, not to create a whellbarrow and rename name it as Mercedes like you say, everything has a starting point. but what you are saying is true I did not notice that PDFBox is a trademark of Apache so whole project is now renamed to PDFLib

**Comment by THausherr** [comment]
PDFLib belongs to [PDFLib GmbH](https://www.pdflib.com/), a german company.
