### ISSUE TITLE
Converting a range of pages fails

### ISSUE THREAD

**Issue by joshbmarshall** [imalhasaranga/PDFLib#3]
If a range of pages is given that does not start with a 1, e.g. if you want to render pages 3 to 5, it gives an error. Specifically ghostscript numbers the output starting with 1 each time and so names the files page1 to page3 rather than page3 to page5.
I have submitted a pull request that fixes this issue

**Comment by joshbmarshall** [comment]
Hi any chance you can accept the pull request? I'm using this in production

**Comment by imalhasaranga** [comment]
I'm reviewing it today, i'm really sorry for being this late

**Comment by imalhasaranga** [comment]
This issue will be resolved with the latest version of the PdfLib.. thank you very much for the support
