### ISSUE TITLE
How to use with cdeigniter?

### ISSUE THREAD

**Issue by Noushid** [imalhasaranga/PDFLib#6]
How to use PDFLib library in codeigniter?

**Comment by imalhasaranga** [comment]
Hi,
I don't have much experience with Codeigniter but since pdfLib is a standard composer package following link should work for you 

https://stackoverflow.com/questions/13741917/how-to-use-composer-packages-in-codeigniter

**Comment by Noushid** [comment]
thank you

**Comment by imalhasaranga** [comment]
Happy to help you 👍
