### ISSUE TITLE
Some Pdf files can't convert to png.

### ISSUE THREAD

**Issue by Noushid** [imalhasaranga/PDFLib#7]
I tried to convert pdf to images (.png) it's work fine ,but some times some files are can't convert.
No error display.

**Comment by imalhasaranga** [comment]
yes can you send the exact code and the pdf ? I'll look at the problem this may happen if the pdf is protected.

**Comment by Noushid** [comment]
that's fixed.
filename problem

**Comment by imalhasaranga** [comment]
:+1:
